### ISSUE TITLE
Adding Server does not work

### ISSUE THREAD

**Issue by Pixelartist** [restcase/apibldr#3]
Hello,

I am trying to add a server, which is currently not working.
After entering all the details, the "add" button is just closing the window.

In addition - the save button seems to not work either (or it is not clear what it saves and where it is saving it).

Windows -> Chrome/Brave/Firefox

**Comment by danielgel** [comment]
Hi @Pixelartist 

Thanks for reporting these issues. 😃 
We will take care of it and update this issue one everything is up and running.

**Comment by danielgel** [comment]
The issue has been resolved and deployed
