### ISSUE TITLE
Create Request Body From JSON is broken

### ISSUE THREAD

**Issue by davidnewcomb** [restcase/apibldr#4]
Component -> Request Bodies -> Create Request Body From JSON.

Dialogue opens like this:

![image](https://user-images.githubusercontent.com/951359/114320124-5ac98080-9b0c-11eb-8959-03b87a7053f6.png)

As you can see there is nowhere to add the example JSON. I tried to tab into the box but couldn't find it, so I couldn't get the button to enable.

Mac Firefox/Chrome

**Comment by danielgel** [comment]
Hey @davidnewcomb

Thanks for reporting the issue. 💪 
I will look into this and will keep you posted once I have some updates.

**Comment by danielgel** [comment]
There was an issue with the `Schema From Example` component.
It is now fixed 
![image](https://user-images.githubusercontent.com/6380461/117834584-f40cc380-b27f-11eb-9972-315ff2f4615a.png)
